### ISSUE TITLE
Remove Colors

### ISSUE THREAD

**Issue by KatieSuth** [KatieSuth/CSC3950-FOSS#1]
Currently, the project attempts to print each line to the screen in a specified color. Printing colors to a command line/terminal is not always supported. For instance, Windows cmd and Powershell do not support printing colors, but accounts for 77.5% of users. Instead of printing colors, it prints garbage.

Powershell - No colors
![powershell-colorgarbage](https://cloud.githubusercontent.com/assets/12041578/24273906/6bf9d418-0ffb-11e7-8c96-d58ce6568b64.PNG)

Cygwin - Colors:
![cygwin-colors](https://cloud.githubusercontent.com/assets/12041578/24273938/94fcc9ce-0ffb-11e7-87b5-782418d31b81.PNG)

Colored printing should be removed since it is not reliable

**Comment by BB-Cait** [comment]
In the console file, I'm not even sure what we should keep, there are already print statements, I'm not sure what to take out and what to leave, so I commented out the section, with the different color functions, and left the print statements, I'm kind confused on what the point of keeping the file is.

**Comment by KatieSuth** [comment]
In my opinion, we just need to comment out wherever the functions in Console.java are called. We could remove the file entirely, but then we'll have errors in the other files because the functions they're calling won't exist. Also, I was thinking repurposing the Console.java file to put my Main function there... but that's in regards to Issue #2.

**Comment by KatieSuth** [comment]
Scratch that, I just saw your pull request. That works too, I'll merge it.
