### ISSUE TITLE
Arraylist Size prints

### ISSUE THREAD

**Issue by BinaryBlacksmith** [KatieSuth/CSC3950-FOSS#7]
When the user adds a value to the Arraylist, it increments the size by 5 rather than actually giving a precise size. Fix by adding a count var to the array add functions.

**Comment by KatieSuth** [comment]
Since we know the index, then we know the actual size is the index + 1. I've fixed it by using this.index + 1 in my code (not yet committed), but I'm wondering what the author meant by size, given that index + 1 is pretty simple?

**Comment by KatieSuth** [comment]
I'm going to commit this code because I think it's what you were aiming for here. I've also updated the labels to make it a little more clear how we're interpreting the different sizes.

**Comment by BinaryBlacksmith** [comment]
Fixed.
